POST  http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1bGxzdGFja29wZW4iLCJpZCI6IjYxZDY3MTRhNDY5M2Y0NzVhN2JlMzJmMCIsImlhdCI6MTY0MTQ0Mzk4NH0.BNvhconcxx_RDHJfMw1IwRUxLcksUlus7OpMwksEtqk


{
    "content": "Sign contract on single page app token authorization",
    "important": true
}

