POST  http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJpc29uIiwiaWQiOiI2MWU1MTZiNjE4NjA2NjNkODE3OTMxZWUiLCJpYXQiOjE2NDI0MDM1MzcsImV4cCI6MTY0MjQwNDQzN30.oy1eqH5qQeb8j9rLynF7l_QVi_Jz9NMgjP1sle6N3Dg

{
    "content": "Gungahlin Town Center",
    "important": true
}

