POST  http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkttYXJ0IiwiaWQiOiI2MWU2MDViYWMyZjY1NTNmZjdiYzVmMzkiLCJpYXQiOjE2NDI0NzU2NDgsImV4cCI6MTY0MjQ5MDA0OH0.Ob3VGbBeRccpTQYXVggrvbGgUWhXXEpGtnjoHj6b4JA

{
    "content": "Cancel home phone end of the month.",
    "important": true
}


